### ISSUE TITLE
Thanks (for lyricwiki plugin) and some suggestions

### ISSUE THREAD

**Issue by Sacolevas** [wildstar84/fauxdacious-plugins#2]
Hello!

THANKS A LOT! It works wonderfully in Fauxdacious my idea of showing local lyrics that you have implemented (and you added the idea of saving locally lyrics from lyrics wiki, which is really great and didn't expected). Hopefully this commit can be implemented in Audacious!

1) On the other hand, using the lyrics wiki plugin has been useful for me because using the "edit lyrics" button I go to the lyricwikia page and I have create lyrics for songs that didn't have one in that page.

So, I think even if local lyrics are shown in the modified plugin, the "edit lyrics" button could be habilitated (no need to grey it out). Some might think that if you have local lyrics, "edit lyrics" could be confused with with edit local lyrics, but if you are a regular user of the plugin you would understand that it would always mean go to the lyricwikia page.

2) Is there a way to package some executable file for Windows so I can test in Windows 10? I definitely wouldn't know (or have time) to compile for Windows as I am not an expert. An additional reason for asking this is that lyricwiki plugin is currently not working in Windows. Somehow the lyricwiki plugin is not picking the lyrics (I don't know why), as reported for several users in Audacious forum.

Thanks a lot again!

**Comment by wildstar84** [comment]
#1) FIXED - Apply latest commit (#6d38956). Reason it was greyed was b/c the "edit lyric" url is fetched in step-2 of a 3-step process, all of which is skipped (and should be) if a local lyric file is found! Anyway, I think I have a workaround that seems to work (for all the cases I tried) that bypasses the search & scrape used normally, but not being very familiar with their site, I can't say for sure it will work in every case.

Like I said, I plan to submit this to Audacious as soon I'm sure we're completely done with getting this working for the best here. Besides, I hope you'll just continue using Fauxdacious (we pretty much have all their features from their latest GIT as we're a "rolling release")! :^)

Oh, and be sure to read the FAQ (first) then give a video file a try, and perhapes give a Youtube video or DVD a try too and/or set some custom song-specific equalizer presets / effects plugins to see what Fauxdacious can really do!

#2 To be honest, I haven't been able to build Fauxdacious in Windows since the last release I did (v3.9-final) as Audacious has changed a bunch of stuff involving icons, etc., and added/changed a bunch of their Windows "patches" and compiling toolchain, causing me to get numerous compiler errors since then. This means in additional to the normal labor required to boot into windows, and build everything, I've got to research all their patch changes, update a bunch of the tools, pray & try again. Now that I have someone actually asking for it (do you actually USE Windows much, or are just wanting to test?), perhaps, when I get ready to call v3.10 "final" (will likely be == Audacious 3.11ish), and have most of a rainy day to spend on it, perhaps I'll take another stab at at.

Cheers,

Jim



     On Friday, October 18, 2019, 7:20:18 PM CDT, Pascual Lucero <notifications@github.com> wrote:  
 
 
Hello!

THANKS A LOT! It works wonderfully in Fauxdacious my idea of showing local lyrics that you have implemented (and you added the idea of saving locally lyrics from lyrics wiki, which is really great and didn't expected). Hopefully this commit can be implemented in Audacious!
   
   - On the other hand, using the lyrics wiki plugin has been useful for me because using the "edit lyrics" button I go to the lyricwikia page and I have create lyrics for songs that didn't have one in that page.

So, I think even if local lyrics are shown in the modified plugin, the "edit lyrics" button could be habilitated (no need to grey it out). Some might think that if you have local lyrics, "edit lyrics" could be confused with with edit local lyrics, but if you are a regular user of the plugin you would understand that it would always mean go to the lyricwikia page.
   
   - Is there a way to package some executable file for Windows so I can test in Windows 10? I definitely wouldn't know (or have time) to compile for Windows as I am not an expert. An additional reason for asking this is that lyricwiki plugin is currently not working in Windows. Somehow the lyricwiki plugin is not picking the lyrics (I don't know why), as reported for several users in Audacious forum.

Thanks a lot again!

**Comment by wildstar84** [comment]
Hi Sacolevas,  
Wanted to email you, but I still don't have your email!  I've finally got the latest 4.0-beta1 built & running on Windows!  It still has a few minor rough edges, but it's working much better than before, and the Lyricwiki part seems to be working now.  You can download the quick GUI installer and give it a try here:  http://phoenixcomm.net/~jturner/Fauxdacious_install.zip  Note:  You may have to add the following 2-line section to your config file if it doesn't pull lyrics or Youtube videos (for the moment):

[neon]
ignore_ssl_certs=TRUE

Regards,
Jim

**Comment by wildstar84** [comment]
Disregard the "ignore_ssl_certs" comment - I fixed it & some other rough-edges & re-released 4.0-beta2 (the Windows installer/binary in the link in the prev. comment) which includes this in the neon plugin configure GUI & properly set).  It should just work now!  Let me know what you think!

**Comment by Sacolevas** [comment]
Hello, 

Thanks a lot!!! I didn't realize the existence of this message until today. Now I have set my email filters in order to see future messages from github easily in my Inbox!

1) I use Windows 10 because I still need Office365 and specially Skype for Business, so in all my computers (both desktop and laptop) I have a dual boot installation using both Windows 10 and Linux Mint XFCE. Consequently, seen this message and the possibility of using Fauxdacious in both operating systems is a great deal. 

2) I currently use Fauxdacious as my audio player in Linux, I will test it in Windows 10 and describe issues if I see one. I ocassionally comment some of these issues in Audacious forum, and it is likely that these issues affect Fauxdacious as well. 

3) On the other hand, concerning using fauxdacious as a video player and also for streaming youtube videos, is something I haven't done. I don't like the Winamp interface so I usually keep the GTK or QT version. But in those interfaces, it seems a bit complicated to watch a video because this video would be on top of the button for controlling audio, unless (perhaps in the future) you have a compact mode. 

4) Finally (for now), I was thinking that the current process to enable video playing and streaming editing lines in the config file seems very complicated. I am not a computer expert or a programmer, but I am capable enough to do some things -for example I created a bash alias in Linux to compile and install Fauxdacious with a single command- and still think is very complicated to follow your instructions in this regard. I have a proposal for you that might facilitate things for users:

a)  I think you could create two plugins, something like  "video playing" and "streaming" so you could activate these options just by clicking on it instead of editing lines manually? It shouldn't be too difficult for you.

b)  And finally, a proposal which could be hard is that as well as the lyricwiki plugin that you could dock or undock, in which video window is contained? (in case you activate video playing). So in this way you could have some sort of compact mode in case you choose to dock the window. This seems to be very difficult unlike (a), but perhaps possible. 

This is all for now. Thanks again, I hope my message was understood completely (English is not my first language) and is highly commendable the enthusiasm for improving and creating options for your program.  Have a nice day.

**Comment by wildstar84** [comment]
Thanks for taking the time to test this stuff out for me!  Replying to your issues:

#3:  You can resize the video window & Fauxdacious should remember the window-size (and aspect), and where you placed it!

#4:  Yes, the docs are somewhat detailed (and I'm updating the FAQ to simplify the "Youtube/Vimeo video" answer to simplify it somewhat in response), but for Windows users, it really is simple - you don't need to edit config files, just go under [Settings].[Advanced] and set the last 3 fields (for any video-playing instances you create) and you should be all set!  Everything else, except possibly some DVD plugin options should default to do what you need to stream and play Youtube, radio, etc.

a:  No need for separate plugins, both should work well (see #3 reply).

b:  This crossed my mind once, as some of the old Winamp (skins) had a cool frame around it's dockable video screen window, with play-back controll buttons too!, but it would be a lot of work to figure out how to build that into Fauxdacious (and a bunch of code on par with the playlist window - and 4 different sets of code (see presets window) for gtk/skinned, qt-skinned, gtk/normal, and qt/normal, so no, not gonna do (just resize and place the video window where you want it, and Fauxdacious should remember) as I like it pretty much as it is (though you can feel free to send me a patch)!

Cheers.

**Comment by Sacolevas** [comment]
Hello! 

Just to report some compilation issues when trying to build fauxdacious from github hoping to see some of the new features in Windows version!

And BTW, I dont really understand the modifications in albumart plugin related to MusicBrainz, how does it work? In which cases can be used?

-------------------------------------
playlist-files.cc: In function ‘bool aud_filename_is_playlist(const char*, bool)’:
playlist-files.cc:49:20: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
             system ((const char *) str_concat ({url_helper, " ", (const char *) filenameBuf, " ", aud_get_path (AudPath::UserDir)}));
             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-stringop-truncation’

eq-preset-qt.cc: In member function ‘void audqt::PresetView::add_imported(const Index<EqualizerPreset>&)’:
eq-preset-qt.cc:218:47: error: cannot convert ‘bool’ to ‘const char*’ for argument ‘2’ to ‘void aud_set_bool(const char*, const char*, bool)’
         aud_set_bool ("equalizer_active", true);
                                               ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-stringop-truncation’
Failed to compile eq-preset-qt.cc (lib)!
../../buildsys.mk:427: recipe for target 'eq-preset-qt.lib.o' failed
make[5]: *** [eq-preset-qt.lib.o] Error 1
../../buildsys.mk:122: recipe for target 'all' failed
make[4]: *** [all] Error 2
../buildsys.mk:135: recipe for target 'libfauxdqt' failed
make[3]: *** [libfauxdqt] Error 2
../buildsys.mk:122: recipe for target 'all' failed
make[2]: *** [all] Error 2
buildsys.mk:135: recipe for target 'src' failed
make[1]: *** [src] Error 2
buildsys.mk:122: recipe for target 'all' failed
make: *** [all] Error 2


PS: In your answer...

#4: Yes, the docs are somewhat detailed (and I'm updating the FAQ to simplify the "Youtube/Vimeo video" answer to simplify it somewhat in response), but for Windows users, it really is simple - you don't need to edit config files, just go under [Settings].[Advanced] and set the last 3 fields (for any video-playing instances you create) and you should be all set! Everything else, except possibly some DVD plugin options should default to do what you need to stream and play Youtube, radio, etc.
 
... do I currently need to edit config files in Linux to enable/disable video and streaming? (I use dual boot between Windows and Linux Mint).


Thanks for your attention and your work improving your program!

**Comment by wildstar84** [comment]
No - you should NOT need to edit any config files in Linux OR Win32 to play videos!  For Youtube, etc.: Linux - you'll need to install the Perl modules and youtube-dl; Windows - install youtube-dl) and set the settings under [Settings].Advanced as specified in the FAQ.

I fixed the compile issues in latest commit - My compiler/version didn't seem to care, but one was a BUG and both should now be fixed in latest commit - thanks for reporting!  

The albumart changes add a setting checkbox under [Plugins].[General].[Album Art].[Settings] that allows for the individual album art image to be loaded for streaming stations by fetching the image from Musicbrainz.com for you each time the song title changes (I think it's kinda cool), if you have the new setting checked!  Please download the latest albumart commit (today) which now multithreads this, since without it, it kinda sucks slightly, and read FAQ#28.

**Comment by wildstar84** [comment]
I'm assuming, due to inactivity, that everything in this issue has now been successfully addressed.

**Comment by wildstar84** [comment]
UPDATE:  youtube-dl will no longer work due to recent Youtube encrapification, you need to get "yt-dlp" from git & install (they have linux binaries)!
