### ISSUE TITLE
glspectrum requires Qt5 and not Qt6

### ISSUE THREAD

**Issue by peutch** [wildstar84/fauxdacious-plugins#5]
Hi,

I am trying to upgrade my (unofficial) Debian packaging on a Sid system and it seems that glspectrum plugin still require Qt5 (libqt5opengl5-dev) and have not been migrated to Qt6.
Should it build be deactivated? In case, how?

Regards,
Patrice

```
printf "Compiling %s (plugin)...\r" "gl-spectrum.cc"
Compiling gl-spectrum.cc (plugin)...
make[6]: Nothing to be done for 'locales'.
in="gl-spectrum.cc"; \
out="gl-spectrum.plugin.o"; \
if g++ -fPIC -DPIC -g -O2 -ffile-prefix-map=/build/reproducible-path/fauxdacious-plugins-4.4.2~final=. -fstack-protector-strong -fstack-clash-protecti
on -Wformat -Werror=format-security -fcf-protection -ffast-math -Wall -pipe -std=gnu++17 -Wtype-limits -Wno-stringop-truncation -Woverloaded-virtual -
fvisibility=hidden -Wdate-time -D_FORTIFY_SOURCE=2  -include config.h  -I../.. -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linu
x-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/us
r/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -DQT_WIDGETS_LIB -
DQT_GUI_LIB -DQT_CORE_LIB    \
     -MD -MF ${out%.o}.dep -c -o gl-spectrum.plugin.o gl-spectrum.cc; then \
        printf "Successfully compiled %s (plugin).\n" "gl-spectrum.cc"; \
else \
        err=$?; printf "Failed to compile %s (plugin)!\n" "gl-spectrum.cc"; exit $err; \
fi
gl-spectrum.cc:31:10: fatal error: QGLWidget: No such file or directory
   31 | #include <QGLWidget>
      |          ^~~~~~~~~~~
compilation terminated.
Failed to compile gl-spectrum.cc (plugin)!
make[6]: *** [../../buildsys.mk:532: gl-spectrum.plugin.o] Error 1
make[6]: Leaving directory '/build/reproducible-path/fauxdacious-plugins-4.4.2~final/src/qtglspectrum'
make[5]: *** [../../buildsys.mk:139: all] Error 2
make[5]: Leaving directory '/build/reproducible-path/fauxdacious-plugins-4.4.2~final/src/qtglspectrum'
make[4]: *** [../buildsys.mk:159: qtglspectrum] Error 2
make[4]: *** Waiting for unfinished jobs....
```

**Comment by wildstar84** [comment]
I myself am currently stuck/frozen in the "TESTING" version of a Debian-derived distro for the last few months waiting on this stupid *-t64 crap to get finished & cleared up, so I don't even have Qt6 installed yet (so can't test).  Anyway, I looked thru the available Qt6 "dev" packages & couldn't find any libqt6opengl*.dev package that looked like a replacement.  I did however find an Audacious commit (#b2e630d) from 4/5/2024 for qtglspectrum that I missed that appears to possibly be related. 

Make sure you have libopengl-dev installed.
Go to src/qtglspectrum/ & run:  "make clean", then:
Replace the last 2 lines in qtglspectrum's Makefile to the following & try recompiling:

CPPFLAGS += ${PLUGIN_CPPFLAGS} -I../.. ${QT_CFLAGS} ${QTOPENGL_CFLAGS} ${GL_CFLAGS}
LIBS += -lm ${QT_LIBS} ${QTOPENGL_LIBS} ${GL_LIBS}

Let me know if that fixes it & I'll commit it.  Otherwise, I can't tell, having not yet been able to install anything Qt6, but you could try building Audacious & seeiing if it throws the same error, if so, report it there.  Either way, post back here any additional info after you try the things I suggested.

Thanks,

Jim

**Comment by wildstar84** [comment]
Hang on, I found another one that changes code, so hold off until I can commit it tomorrow, will post back...

**Comment by wildstar84** [comment]
Ok, Install latest commit (#f30e0c9), switch to the qtglspectrum subdirectory & try:  make clean; make.  Then try to recompile 
the rest of it (from the fauxdacious-plugins directory), if successfull, install & close this.  Otherwise report back here!

**Comment by peutch** [comment]
Great, it builds fine now!

**Comment by wildstar84** [comment]
Awesome sause - Thanks for reporting!
